{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "opencode-web.fullname" . }}
  labels:
    {{- include "opencode-web.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.hostname }}
  host: {{ .Values.route.hostname }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "opencode-web.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None
{{- end }}
