apiVersion: v2
name: opencode-web
description: A Helm chart for deploying Opencode Web (with OpenChamber) on OpenShift
type: application
version: 0.2.0
appVersion: "1.17.4"
maintainers:
  - name: Marco Caimi
keywords:
  - opencode
  - web
  - ai
home: https://github.com/anomalyco/opencode
